### ISSUE TITLE
Reference `bash` instead of `sh`

### ISSUE THREAD

**Issue by asieira** [jed/certbot-route53#2]
I've had problems in Ubuntu because the script begins with `#!/bin/sh` but uses bash-specific syntax. I would like to recommend that the first line is instead changed to `#!/usr/bin/env bash` as per https://stackoverflow.com/a/10383546/2482776.

**Comment by jason-klein** [comment]
Thank you for this script! Works great on our private AWS servers! Our Debian default shell is not bash, so we had to make same adjustment @asieira mentioned above.
