### ISSUE TITLE
SERVFAIL looking up TXT for _acme-challenge.remcam.io

### ISSUE THREAD

**Issue by svanschalkwyk** [jed/certbot-route53#4]
Hi,
Thank you for the script.
I have been trying Certbot manually and using your script.
While it is running, Route 53 shows the TXT being created AND removed.
However, it seems that Route 53 will not allow queries for the TXT record.
The script produces this: 

"Failed authorization procedure. nginx.remcam.io (dns-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up TXT for _acme-challenge.nginx.remcam.io, remcam.io (dns-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: SERVFAIL looking up TXT for _acme-challenge.remcam.io
"
Any idea what is going on?

**Comment by jed** [comment]
no idea, sorry. 🙇

**Comment by brucejs** [comment]
Banging my head against the wall with this same problem

**Comment by itpick** [comment]
same problem

**Comment by itpick** [comment]
resolution: https://stackoverflow.com/questions/37533568/new-domain-is-both-registered-with-and-hosted-at-aws-route-53-but-resolution-fai/37534217#37534217
